### ISSUE TITLE
support dependency caching

### ISSUE THREAD

**Issue by avsm** [ocaml/setup-ocaml#1]
We can't do action caching right now since the Windows/cygwin/fdopen one fails when using an opam local switch.  Once local switches work there, it should be possible to create an `_opam` directory and cache that for the dependencies.

**Comment by imbsky** [comment]
I'm not familiar with Windows, is it the GitHub Actions side that is blocking this? or is it something else?

**Comment by Amar1729** [comment]
In the meantime, is it possible to enable caching of any opam switches created on darwin/linux?

**Comment by imbsky** [comment]
It will be possible if you do it personally. But there are no plans to add feature to the action that supports only certain platforms. Also, since it turned out that it was not a very realistic solution, I started some experimental projects to solve the problem.

**Comment by jfrolich** [comment]
It's pretty easy to use `actions/cache@v2` to cache some directories. This will make builds **much** as all that happens in this actions (setting up ocaml) can be cached and done only once.

**Comment by jfrolich** [comment]
It works pretty well with linux. For windows what is the issue with a local cache, has that been resolved already?

**Comment by smorimoto** [comment]
I do maintenance on actions/cache lately, so I know it well. I don't have much time this month, but I can implement this next month if things go well.

**Comment by smorimoto** [comment]
v2 uses a local switch, so we can support it. Although it will not yet be fully supported due to per-repository cache size limit.
