### ISSUE TITLE
Clearer README

### ISSUE THREAD

**Issue by aantron** [ocaml/setup-ocaml#158]
Some brief usage example should come first in the README, along with only keywords like "caching" and "including Windows support." The details of everything setup-ocaml does should come nearly last, in some kind of reference section.

The current README doesn't "sell" the action. A reader coming to the repo doesn't know what using this action *really* entails from the reader's point of view. Is it difficult? Is it neat?

**Comment by dra27** [comment]
Agreed. I think is just a case of taking the Action and Usage sections from v1 (see [pre-v2 merge](https://github.com/ocaml/setup-ocaml/tree/25608863085910e9c2683873047587fe0e92099a#set-up-ocaml) and updating them.

**Comment by smorimoto** [comment]
I just updated a little bit overall, what do you think about that?

**Comment by aantron** [comment]
Looks nice to me right now!

**Comment by smorimoto** [comment]
I'm glad to hear that! If you have any ideas for improvement in the future, please feel free to open an issue or PR!
