### ISSUE TITLE
libidn update broke the action workflow on Windows

### ISSUE THREAD

**Issue by smorimoto** [ocaml/setup-ocaml#195]
curl relies on libidn and is temporarily broken by the update, namely it complains about curl missing.

**Comment by dra27** [comment]
This was a packaging mistake which has been [fixed upstream](https://cygwin.com/pipermail/cygwin/2021-August/249045.html). It's propagating to mirrors: setup.ini with a timestamp on or after 20210803 16:21:27+0000 is working.

**Comment by dra27** [comment]
One thing we _could_ do is to adopt a trick used in opam and ocaml's AppVeyor scripts (see [appveyor_build.cmd](https://github.com/ocaml/ocaml/blob/trunk/tools/ci/appveyor/appveyor_build.cmd#L100-L128) in ocaml/ocaml). There, you have `CYGWIN_PACKAGES` containing the name of a package (e.g. `mingw64-x86_64-gcc-core`) which is required along with a command which should be run to check it in `CYGWIN_COMMANDS` (e.g. `x86_64-w64-mingw32-gcc`). The assumption is that `x86_64-w64-mingw32-gcc --version` should return an exit code of `0` but it will fail if there's a DLL which can't load - just like has happened here. So we could use that second part to test the Cygwin installation to display a better error message should this happen again.

**Comment by dra27** [comment]
(it could be tested with the glorious-website-named [Cygwin Time Machine](http://www.crouchingtigerhiddenfruitbat.org/Cygwin/timemachine.html#cygwintimemachine))

**Comment by smorimoto** [comment]
It's completely resolved as it was updated on the mirror server that setup-ocaml currently uses.
