### ISSUE TITLE
setup-ocaml started failing on macOS-10.15

### ISSUE THREAD

**Issue by daniel-larraz** [ocaml/setup-ocaml#236]
Our scheduled github workflow [started failing](https://github.com/kind2-mc/kind2/runs/3524897491?check_suite_focus=true) today with the following error:
```
  ==> Installing mercurial dependency: python@3.9
  ==> Pouring python@3.9--3.9.7.catalina.bottle.tar.gz
  Error: The `brew link` step did not complete successfully
  The formula built, but is not symlinked into /usr/local
  Could not symlink bin/2to3
  Target /usr/local/bin/2to3
  already exists. You may want to remove it:
    rm '/usr/local/bin/2to3'
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite python@3.9
  
  To list all files that would be deleted:
    brew link --overwrite --dry-run python@3.9
  
  Possible conflicting files are:
  /usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/2to3
```
It [was working](https://github.com/kind2-mc/kind2/runs/3516856483?check_suite_focus=true#step:5:32) fine yesterday. Workflow file: https://github.com/kind2-mc/kind2/blob/develop/.github/workflows/kind2-nightly.yml#L79

**Comment by smorimoto** [comment]
This seems to be rather a problem between brew and macOS, so I would suggest reporting on the brew side.

**Comment by daniel-larraz** [comment]
Thank you @smorimoto. I changed the workflow so that it does not update the package information (`brew update`) before running the ocaml-setup step. That solves the issue for now.
