### ISSUE TITLE
new failures on windows?

### ISSUE THREAD

**Issue by c-cube** [ocaml/setup-ocaml#264]
since 4.13 was released, I've started seeing [this kind of failure](https://github.com/c-cube/ocaml-containers/runs/3709650152?check_suite_focus=true), where setup-ocaml tries to install ocaml 4.13 but fails (even on switches explicitly using another version of the compiler).

**Comment by shonfeder** [comment]
We are seeing the same kind of failure, but for 4.12:

```
ocaml-variants = 4.12.1+mingw64c no matching version
```

https://github.com/ocaml/omd/pull/254/checks?check_run_id=3710546953#step:3:589

**Comment by dra27** [comment]
For 4.13, it's (genuinely!) great that systems are so ready the weekend after the release! Unfortunately, that's caught us out slightly with [discontinuation](https://fdopen.github.io/opam-repository-mingw/2021/02/26/repo-discontinued/) of [fdopen/opam-repository-mingw](https://github.com/fdopen/opam-repository-mingw).

This affects 4.12.1 and 4.13.0 - it should be temporarily possible to work around this by forcing 4.12.0 for Windows in your build matrix and removing 4.13.0.

I'm in the process of sorting out the formal upstreaming of Windows support to `ocaml-base-compiler` in ocaml/opam-repository (actually working on it yesterday, as part of a demo for cloneable compiler for opam on Tuesday), but I'll try to put a temporary update of the patches together for setup-ocaml to use either this evening or tomorrow.

**Comment by smorimoto** [comment]
In the short term, https://github.com/fdopen/opam-repository-mingw/commit/2b57e0dcf375f131ab2fb956bffa79eba5d20b2c should have fixed things. In the long term, I will fix this with https://github.com/ocaml/setup-ocaml/issues/263...

**Comment by smorimoto** [comment]
The new release contains a fix for this issue. So it will not happen in future releases. Thanks for the report!

**Comment by shonfeder** [comment]
Thanks for the fix!
