### ISSUE TITLE
Allow to choose opam version

### ISSUE THREAD

**Issue by bikallem** [ocaml/setup-ocaml#299]
Is there a way to choose opam version, i.e. 2.0, 2.1 etc?

**Comment by smorimoto** [comment]
If you need opam 2.1 a little early, I can implement one to support that, but if you don't really need it, I won't add it to keep the implementation simple, how about it?

**Comment by bikallem** [comment]
> If you need opam 2.1 a little early, I can implement one to support that, but if you don't really need it, I won't add it to keep the implementation simple, how about it?

opam 2.1 would be most awesome as we want to use it for https://github.com/ocaml-multicore/tezos.

**Comment by dra27** [comment]
opam 2.1.1 is driving through the release process, and once https://github.com/ocaml-opam/opam-depext/pull/142 is merged and released, I’d recommend we switch MacOS and Linux to use 2.1.1 by default and just allow users to override the default setting of `OPAMCLI` to `2.0`

**Comment by dra27** [comment]
opam 2.1.1 is driving through the release process, and once https://github.com/ocaml-opam/opam-depext/pull/142 is merged and released, I’d recommend we switch MacOS and Linux to use 2.1.1 by default and just allow users to override the default setting of `OPAMCLI` to `2.0`.

**Comment by smorimoto** [comment]
I don't plan to let you choose any opam version at this point, but we can re-visit this once the native Windows opam is released. For now, close this.
