### ISSUE TITLE
Error: Cannot destructure property `browser_download_url` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by sim642** [ocaml/setup-ocaml#304]
"Install opam" step fails with:
```
 Error: Cannot destructure property `browser_download_url` of 'undefined' or 'null'.
```
For example:
https://github.com/goblint/analyzer/runs/4117329948?check_suite_focus=true#step:3:19.

This causes all workflows to immediately fail!

**Comment by smorimoto** [comment]
Could you try it again? It appears it attempted to install opam 2.0.10 but failed because it does not have any assets. But it's now fixed! https://github.com/ocaml/opam/releases/tag/2.0.10

**Comment by sim642** [comment]
You're right, it is fine now.

I suppose this action could be hardened to not mysteriously fail when a new opam version is half-released by falling back to the previous one which is fully available.

**Comment by smorimoto** [comment]
That's actually a good point, and that's exactly what I was going to do next!
