### ISSUE TITLE
On Windows, the explicit depext install step is needed.

### ISSUE THREAD

**Issue by MisterDA** [ocaml/setup-ocaml#351]
On Windows we still use opam 2.0, which works with the depext plugin.
You have to run

```shell
opam depext -i .
```

before this step

```shell
opam install . --deps-only --with-test
```
if I'm not mistaken.

There's some more packages to install, and the `PATH` to configure, see [depext cygwin](https://fdopen.github.io/opam-repository-mingw/depext-cygwin/).

**Comment by smorimoto** [comment]
All required packages are handled properly here:
https://github.com/ocaml/setup-ocaml/blob/71de13677683a0cae38afd87c782e070a7bdbc0e/src/setup-ocaml/depext.ts#L8-L24

and the action performs depext processing by default:
https://github.com/ocaml/setup-ocaml/blob/71de13677683a0cae38afd87c782e070a7bdbc0e/src/setup-ocaml/depext.ts#L26-L31
https://github.com/ocaml/setup-ocaml/blob/71de13677683a0cae38afd87c782e070a7bdbc0e/src/setup-ocaml/installer.ts#L148

**Comment by hcarty** [comment]
I'm having a similar issue trying to get `setup-ocaml@v2` working on Windows.

An example failure, with `conf-pkg-config` asking for an explicit `depext` call:
https://github.com/orx/ocaml-orx/runs/4681002758?check_suite_focus=true

**Comment by smorimoto** [comment]
Wow, it's pretty weird that it does not work as I expected. Let me take a deep look at it.

**Comment by hcarty** [comment]
Thank you @smorimoto!

**Comment by smorimoto** [comment]
@hcarty Your case seems to be a slightly different case from this one. I left some comments!

**Comment by smorimoto** [comment]
In fact, explicit depext is still enabled on all platforms, so it should work properly, unless you configure it incorrectly. I will close this issue, but please leave a comment if you think I misunderstood something.

**Comment by hcarty** [comment]
Thank you for your help in identifying and addressing the issue with my project's use of `setup-ocaml` - I appreciate it!

**Comment by smorimoto** [comment]
Anytime!

**Comment by MisterDA** [comment]
I think the issue I wanted to report was like the one from @hcarty, but I can't find the original error. If I do, I'll report again.

**Comment by smorimoto** [comment]
I see, thank you!
