### ISSUE TITLE
List of supported Ubuntu versions?

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/setup-ocaml#36]
Hi! Thank you for creating and maintaining this great project!

It would be great to see the list of Ubuntu versions that are currently supported (I hope I didn't miss it).
Right now I only see `ubuntu-latest` which is Ubuntu 18.04 at the time of writing, but what about 16.04 and 20.04?

Perhaps seeing the versions of the other OSes would be also useful.

**Comment by artob** [comment]
Indeed, on Ubuntu 16.04 this fails due to the Bubblewrap issue:

<img width="780" alt="Screen Shot 2020-09-09 at 20 55 14" src="https://user-images.githubusercontent.com/4963/92635703-f11b9680-f2de-11ea-8604-07e07bb13689.png">

**Comment by smorimoto** [comment]
I'm sorry I'm so late. (I was doing other cache-related work at the same time.) The result is that this will be fixed in the next version.

**Comment by smorimoto** [comment]
It's no longer automatically installed in 16.04, and there is an extra input to disable sandboxing.

**Comment by smorimoto** [comment]
The functionality to disable sandboxing will be introduced in v2, so you should be able to avoid this problem.
