### ISSUE TITLE
CAfile issue on Windows?

### ISSUE THREAD

**Issue by phated** [ocaml/setup-ocaml#382]
I'm not sure if this belongs here or somewhere else (or if there's a bug in some other part of the GitHub Actions system).

I just tried to [run a build](https://github.com/grain-lang/libbinaryen/runs/4709403690?check_suite_focus=true) on `windows-latest` and got this failure:

```
Initialise the opam state
  D:\cygwin\bin\opam.exe init --auto-setup --bare --disable-sandboxing --enable-shell-hook
  [NOTE] Will configure from built-in defaults.
  Checking for available remotes: rsync and local, git, mercurial.
    - you won't be able to use darcs repositories unless you install the darcs command on your system.

  <><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
  [ERROR] Could not update repository "default": "D:\\cygwin\\bin\\git.exe fetch -q" exited with code 128 "fatal: unable to access 'https://github.com/fdopen/opam-repository-mingw.git/': error setting certificate verify locations:  CAfile: /etc/pki/tls/certs/ca-bundle.crt CApath: none"
```

It happened on two runs, so I wanted to raise it as a potential issue.

**Comment by smorimoto** [comment]
It seems like an upstream issue. I would probably want to ask in the virtual-environment repository.

**Comment by phated** [comment]
@smorimoto I can take a look, but isn't this happening *inside* the cygwin that setup-ocaml provides?

**Comment by phated** [comment]
I found [this thread](https://cygwin.com/pipermail/cygwin/2015-September/223731.html) on the cygwin mailing list that says this error is a problem with the cygwin install.

**Comment by smorimoto** [comment]
It's a pretty old thread, so I don't know if it really has anything to do with this. Also, I don't see such an error at the moment, so it's quite weird.

**Comment by dra27** [comment]
@phated - are you able to try #384? (i.e. use dra27/setup-ocaml@cygwin-setup)

**Comment by phated** [comment]
Thanks @dra27!

**Comment by dra27** [comment]
No problem - as it happens, the maintainer of Cygwin's setup program has also very rapidly rolled out a fix!

**Comment by c-cube** [comment]
Is this fix deployed already, or do we need to wait for the next release of `v2.0.0-betaxxx`?

**Comment by dra27** [comment]
Cygwin setup’s been patched, although I don’t know if it’s deployed yet (both setup 2.913 and 2.914 address the issue)

**Comment by c-cube** [comment]
I'm asking because I see this kind of failures: https://github.com/c-cube/iter/runs/4745117247?check_suite_focus=true :)

**Comment by smorimoto** [comment]
@c-cube @hhugo I just released a new release. Please try to see if it works as expected.
https://github.com/ocaml/setup-ocaml/releases/tag/v2.0.0-beta12

**Comment by c-cube** [comment]
All green, thanks! :)
