### ISSUE TITLE
Random package install failures in MacOS CI actions

### ISSUE THREAD

**Issue by mooreryan** [ocaml/setup-ocaml#400]
So I know this won't be a very useful issue description, but on multiple actions across multiple repositories, I will randomly get failures on the MacOS.

For example, I will have a step in the action like this...

```
opam exec -- opam install . --jobs 1 --deps-only --with-doc --with-test
```

And there will often be a random package install failure e.g.,

```
┌─ The following actions failed
│ λ build ppxlib 0.24.0
└─ 
```

Generally it will be a different package that will fail to install each time the action is run.  Often, if I rerun the action once or twice it will clear up any problems.

I'm having trouble reproducing this issue as the same action will be totally fine for many commits/runs and then it will randomly fail a couple of times, then be totally fine for the next few runs.

I'm wondering if anyone else has run into this and if so, is there a way to fix it other than just re-running failed actions?

**Comment by smorimoto** [comment]
Maybe you are enabling the dune cache? The current dune 2 is buggy with the dune cache, which is completely fixed in the upcoming dune 3, and that's why we don't enable the dune cache by default at the moment.

**Comment by smorimoto** [comment]
Related PRs:
- https://github.com/ocaml/dune/pull/4443
- https://github.com/ocaml/dune/pull/4465
- https://github.com/ocaml/dune/pull/4484
- https://github.com/ocaml/dune/pull/4498
- https://github.com/ocaml/dune/pull/4576

**Comment by mooreryan** [comment]
Thanks, I will take a look at that and report back!

**Comment by smorimoto** [comment]
Resolved with https://github.com/ocaml/opam-repository/pull/20758.
