### ISSUE TITLE
Many warnings on macos-latest and ubuntu-latest

### ISSUE THREAD

**Issue by mgree** [ocaml/setup-ocaml#432]
During the OPAM install for 4.13.x (and other versions too), there are _many_ warnings, both on [macos-latest](https://github.com/mgree/libdash/runs/5324229594?check_suite_focus=true#step:3:323) and [ubuntu-latest](https://github.com/mgree/libdash/runs/5324229649?check_suite_focus=true#step:3:238).

None of these warnings are harmful causing failures, but they make finding _other_ failures hard.

**Comment by smorimoto** [comment]
It's not a real issue with the Action, but in some sense, with opam-repository. That being said, more importantly it's not a real issue even with opam-repository. I understand that they are annoying with search, but I don't know how to actually make it go away.
@kit-ty-kate Do you have any ideas?

**Comment by kit-ty-kate** [comment]
I’m not sure where these warnings come from, they don’t appear in normal operation nor in opam-repo-ci for example.
Could you list which `OPAM*` environment variables setup-ocaml has?

**Comment by smorimoto** [comment]
The environment variables we are handling for the current system are:.

```json5
{
  "common": {
    "OPAMCLI": "2.0",
    "OPAMCOLOR": "always",
    "OPAMERRLOGLEN": 0,
    "OPAMJOBS": "(Number of logical CPU cores)",
    "OPAMPRECISETRACKING": 1,
    "OPAMSOLVERTIMEOUT": 1000,
    "OPAMVERBOSE": (true | false), // Depends on whether action step debugging is on
    "OPAMYES": true,
    "DUNE_CACHE": true,
    "DUNE_CACHE_TRANSPORT": "direct"
  },
  "windows-specific": {
    "OPAMROOT": "D:/.opam",
    "HOME": "process.env.USERPROFILE",
    "MSYS": "winsymlinks:native"
  }
}
```

**Comment by liyishuai** [comment]
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Consider updating actions/checkout to v3.
