### ISSUE TITLE
Failing on Ubuntu as apt shifts the ground under our feet

### ISSUE THREAD

**Issue by mgree** [ocaml/setup-ocaml#438]
I just got a spurious failure on Ubuntu, where the OCaml setup fails because certain files are no longer accessible on their mirrors. ([logs](https://github.com/mgree/kmt/runs/5396167190?check_suite_focus=true))

Forcing an `apt-get update` beforehand seems to resolve the issue. ([logs](https://github.com/mgree/kmt/runs/5396849763?check_suite_focus=true))

It would be great to have these scripts work _without_ `apt-get update`... though it seems like an upstream issue and hard to address here.

Would it be a good idea to detect so many 404s and suggest an `apt-get update` (with a commensurate warning about reproducibility)?

**Comment by smorimoto** [comment]
That's a great idea! Let me implement it soon!

**Comment by smorimoto** [comment]
@mgree @leviroth Thank you for your report! For Linux and macOS, we have fixed to update the index if the package installation fails. The v2 tag has already been moved, so you should be able to try it as is.

**Comment by mgree** [comment]
It works! ([logs](https://github.com/mgree/kmt/runs/5408539841?check_suite_focus=true#step:3:82))

Thank you for the speedy turnaround time and a lovely fix. 😁

**Comment by smorimoto** [comment]
Awesome! Anytime!
