### ISSUE TITLE
Cache keys

### ISSUE THREAD

**Issue by favonia** [ocaml/setup-ocaml#528]
1. Due to https://github.com/actions/cache/issues/2 I need to use some hack to manually clear the cache of a broken OCaml 5 build, but I could not find the cache keys without digging into the source code. Could we possibly have all the keys documented somewhere?
2. To solve my immediate problem I _did_ dig into it. However, I'm confused by the current naming schemes. It seems the code is appending non-essential, changing information such as dates (years, weeks, and dates) and workflow run identifiers (run ids, run numbers) to the cache keys. I believe the keys should contain only essential information, and we should simply overwrite older copies. The only reason I could think of for attaching non-essential info is to using the older copies of the OPAM repositories, but this means the cache is potentially changing the semantics of the CI: even with the cache, the CI should always try to approximate "building and running the code from scratch now" as much as possible.

**Comment by smorimoto** [comment]
The underlying problem is that you can't overwrite the old cache. In the meantime, these are pretty deep and well figured cache keys that are still needed.

**Comment by favonia** [comment]
Hi I am closing this because I don't have time working on this now, and the CI will work correctly regardless of the final decision. (This issue is about improving efficiency, not correctness.)
