### ISSUE TITLE
frozen versions?

### ISSUE THREAD

**Issue by c-cube** [ocaml/setup-ocaml#534]
Hi,

I like setup-ocaml and I use it in many projects. However, it tends to break when the underlying systems are updated (currently #529, previously in my case #361, #264, #479). I would love a way to specify a fixed version that uses a fixed underlying OS, even if it means I have to upgrade the version from time to time (e.g. `ocaml/setup-ocaml@v2.16`, update to `@v2.17` if the OS dependencies get too old).

Is that even a remote possibility, or structurally impossible?

**Comment by smorimoto** [comment]
In fact, it's possible to have fairly strict version control of the action by specifying tags. For example: `ocaml/setup-ocaml@v2.0.3`, `ocaml/setup-ocaml@v2.0.4`.
