### ISSUE TITLE
Uses discontinued repository on Windows

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/setup-ocaml#547]
I've been submitting an update to Merlin https://github.com/ocaml/merlin/pull/1475 which uses Yojson 2.0.0. It turns out the CI on Windows fails because Yojson 2.0.0 is not available.

Further inspection shows that it uses https://github.com/fdopen/opam-repository-mingw.git#opam2 which is [apparently discontinued](https://fdopen.github.io/opam-repository-mingw/2021/02/26/repo-discontinued/). That probably means that there won't be many if all updates going forward. Though even despite the blog post stating August 2021 there still seems to be activity in that repository.

Looking at the source code
https://github.com/ocaml/setup-ocaml/blob/99ffdbe56b436bc6c29c803570b158d347765af6/src/setup-ocaml/constants.ts#L69-L72
this seems to be a deliberate decision, hence I am opening this ticket to discuss what's the best way to go forward with this.

**Comment by Alizter** [comment]
What is the planned OCaml support for Windows? I hear that opam 2.2 is intending to have Windows support, but I also have heard that 2.0 and 2.1 have also made this promise.

**Comment by Leonidas-from-XIV** [comment]
So it turns out that the repo is still updated, but sometimes lags behind opam-repository. @fdopen, could you please weight in with an update on what the status of that repository is?

**Comment by johnridesabike** [comment]
This just bit me after I upgraded ocamlformat and `opam install` stopped working on Windows (but kept working on MacOS and Linux). Debugging this can be quite confusing if you don't know what's going on.

If a fix isn't imminent, then it may be at least helpful to include a disclaimer about Windows and OPAM in the Readme?
