### ISSUE TITLE
Cache doesn't work on Windows

### ISSUE THREAD

**Issue by Alizter** [ocaml/setup-ocaml#552]
Cache doesn't seem to work on windows.

https://github.com/ocaml/dune/pull/5902

**Comment by smorimoto** [comment]
Is this still happening?

**Comment by Alizter** [comment]
I've restarted the CI to check. Let's see.

**Comment by Alizter** [comment]
Still an issue: https://github.com/ocaml/dune/actions/runs/3556354047/jobs/5973655970

**Comment by Alizter** [comment]
@smorimoto Can you reopen this?
