### ISSUE TITLE
Opam Dependency Submission

### ISSUE THREAD

**Issue by c-cube** [ocaml/setup-ocaml#554]
This [^1] is new and might be interesting to have github understand OCaml repos, for example if setup-ocaml had an optional step to declare package structure (e.g. one manifest per opam package in the repo).
What do you think?

[^1]: https://github.blog/2022-06-17-creating-comprehensive-dependency-graph-build-time-detection/

**Comment by smorimoto** [comment]
Interesting! I will take a look at it!

**Comment by smorimoto** [comment]
https://github.blog/changelog/2023-03-24-dependency-graph-graphql-api-preview-includes-submitted-dependencies/

**Comment by smorimoto** [comment]
https://github.com/github/advisory-database/issues/1897
