### ISSUE TITLE
OPAM CI and setup-ocaml differ in treatment of depexts on macOS?

### ISSUE THREAD

**Issue by mgree** [ocaml/setup-ocaml#594]
Right now libdash-0.3 builds in OPAM CI but not in GitHub CI. There are a number of issues, but one of them seems to be how external dependencies are treated on macOS, namely that `conf-aclocal` isn't installing `automake`.

When running in the OPAM CI, depexts are installed at the beginning of the procedure, like you'd expect ([CI run](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/db9011d51d0d27b6ebdc47da7e23bbf618542420/variant/distributions,macos-homebrew,libdash.0.3)).

When running in the GitHub CI, virtual packages for depexts are run inline and fail their tests without invoking the host package manager ([CI run on macOS 11](https://github.com/mgree/libdash/runs/7591852085?check_suite_focus=true); [CI run on macOS 12](https://github.com/mgree/libdash/runs/7591852039?check_suite_focus=true); grep for `automake`).

Am I invoking things wrong, or is there a real discrepancy in the environment?

(I originally [filed an issue on `opam-repository`](https://github.com/ocaml/opam-repository/issues/21921), but it seems likely that this is an issue with `setup-ocaml`'s treatment of depexts.)

**Comment by smorimoto** [comment]
I think it's probably due to our use of opam 2.0 mode with opam 2.1. There aren't many clear solutions right now and we're just waiting for the 2.2 release with native Windows support. CC: @dra27

**Comment by dra27** [comment]
opam-ci is using opam 2.1, which has integrated support for invoking the package manager. setup-ocaml uses opam 2.0 at the moment - you just need to add a call to `opam depext libdash` before `opam install` in the workflow file (or call the package manager directly to install automake).

**Comment by mgree** [comment]
Thank you! This exact workaround was suggested over on the original issue, and it solves that problem. (It doesn't solve my other problems, but that's on me. 😅)

It may not be worth it if this is a temporary difference, but it might be good to mention this difference in docs. Or, stronger still, to automatically do it unless disabled by a flag in the workflow.
