### ISSUE TITLE
add option to disable opam sandboxing

### ISSUE THREAD

**Issue by sykhro** [ocaml/setup-ocaml#6]
It would be useful to have an option to init opam with the `--disable-sandboxing` flag, allowing this action to be used inside docker containers

**Comment by avsm** [comment]
That sounds useful. Out of interest, can you use this action within a GH Action in Docker mode, or is this for running the action locally?

**Comment by imbsky** [comment]
This action should also work in Docker mode.

**Comment by sykhro** [comment]
Running this in Docker on GH Actions I couldn't get past the opam init

**Comment by imbsky** [comment]
Yes, of course it probably depends on the image you use.

**Comment by imbsky** [comment]
@avsm If you agree with this idea, I will add an implementation for this. Well, it will be implemented as an input only available on Ubuntu and macOS, as there is no option other than disabled on Windows.

**Comment by smorimoto** [comment]
This will be supported in the next version.

**Comment by Risto-Stevcev** [comment]
+1 on this, would be really useful for testing [locally](https://github.com/nektos/act)

**Comment by smorimoto** [comment]
The functionality that allows us to do this will finally be introduced in v2.

**Comment by smorimoto** [comment]
https://github.com/avsm/setup-ocaml/blob/v2/examples.md#using-with-containers
