### ISSUE TITLE
Support for old versions of OCaml (≤ 3.12)

### ISSUE THREAD

**Issue by thierry-martinez** [ocaml/setup-ocaml#615]
`setup-ocaml` doesn't work with old versions of OCaml (≤ 3.12). (It was already noted in the issue https://github.com/ocaml/opam-repository/issues/22015 which was transferred to opam-repository, but this part of the issue seems to be specific to `setup-ocaml`.)

- With 3.07, it fails with the message `Error: No OCaml base compiler packages matched the version 3.07 in the opam-repository.`, whereas `opam switch create 3.07` should work as expected (https://github.com/thierry-martinez/stdcompat/runs/7952973003?check_suite_focus=true).
- With OCaml 3.08 to 3.12, it seems to fail because it tries to install `opam-depext` which requires OCaml ≥ 4.00.

**Comment by smorimoto** [comment]
Since opam-depext can be controlled from the input, it should be relatively easy to turn it off. Are there any other issues left?
