### ISSUE TITLE
Pb with conf-libssl and macos

### ISSUE THREAD

**Issue by craff** [ocaml/setup-ocaml#638]
opam package conf-libssl try to install openssl on macos and the package is not found.
I don't think this is an issue with conf-libssl as [openssl seems to exist](https://formulae.brew.sh/formula/openssl@3)
```
#=== ERROR while compiling conf-libssl.4 ======================================#
# context     2.1.4 | macos/x86_64 | ocaml-base-compiler.5.0.0 | git+https://github.com/ocaml/opam-repository.git
# path        ~/work/simple_httpd/simple_httpd/_opam/.opam-switch/build/conf-libssl.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh -ex ./homebrew.sh check
# exit-code   1
# env-file    ~/.opam/log/conf-libssl-39818-0312a6.env
# output-file ~/.opam/log/conf-libssl-39818-0312a6.out
### output ###
# ++ brew --prefix openssl
# + brew_pkg_config=/usr/local/opt/openssl@3/lib/pkgconfig
# + case "$1" in
# + test 1 '!=' 1
# + export PKG_CONFIG_PATH=/usr/local/opt/openssl@3/lib/pkgconfig:/Users/runner/work/simple_httpd/simple_httpd/_opam/lib/pkgconfig
# + PKG_CONFIG_PATH=/usr/local/opt/openssl@3/lib/pkgconfig:/Users/runner/work/simple_httpd/simple_httpd/_opam/lib/pkgconfig
# + pkg-config --print-errors --exists openssl
# Package openssl was not found in the pkg-config search path.
# Perhaps you should add the directory containing `openssl.pc'
# to the PKG_CONFIG_PATH environment variable
# No package 'openssl' found
```

**Comment by craff** [comment]
This solved the issue:
```
      - run: brew install openssl@3
        if: ${{ matrix.os == 'macos-latest' }}
```
May be a problem with conf-libssl in the end. I update my issue there.

**Comment by ivg** [comment]
I think that the proper place for such issues (including #637) should go to https://github.com/ocaml/opam-repository/issues

**Comment by craff** [comment]
I am not sure for #637. depext is not supposed to do apt-get update for you. Only apt-get install. 
I think the building of the container should include an apt-get install otherwise there is always a risk of 
an ubuntu package not available, even if the base container is updated regularly, if you try to build at the wrong time
you get missing packages. 

I copy this comment in #636 where it belongs.

**Comment by craff** [comment]
I agree that this probably is not an issue with ocaml-setup in the end. I think it is more a problem
of conf-libssl not declaring its dependencies correctly, but I will report to opam too, thanks for the advice. 

I close the issue.

**Comment by smorimoto** [comment]
This kind of problem is not just `setup-ocaml` or `opam`, but rather a runner image problem in shaky GitHub Actions. While setup-ocaml currently takes care of updating the index if the system package manager causes an error during the process of setting up the `opam` environment, then this appears to be a rare case that sneaked through. I could change it to update the index every time by removing the complex mechanism mentioned above, but I'm still not sure which path is right. Let me think about this for a moment.
