### ISSUE TITLE
why is depext not invoked on `opam install`?

### ISSUE THREAD

**Issue by ivg** [ocaml/setup-ocaml#639]
Since opam 2.1.0 `opam install foo` will automatically install the system dependencies as well, so we don't need to do `opam depext --install foo`. I know that commonly depexts are dispatched by this workflow during the setup-ocaml action based on the opam packages that are pinned in the checked out repository. However, one of my workflows doesn't pin any packages and just installs packages from opam repositories. It fails though, as `opam install bap-extra` doesn't [even make an attempt][1] to check or install the missing dependencies. Is this because opam in the action is configured in a such way? I grepped through the repo but failed to find any evidence of this.

[1]: https://github.com/BinaryAnalysisPlatform/bap/actions/runs/3896202255/jobs/6653131366#step:4:18

**Comment by smorimoto** [comment]
To be more clear, it's to set up the environment in exactly the same way as Windows, which will change in the next opam minor release.
For the time being, that might be possible by forcing opam to behave as 2.1 by executing the following command in a step after setup is complete.

```bash
echo "OPAMCLI=2.1" >>"$GITHUB_ENV"
```

https://github.com/ocaml/setup-ocaml/blob/5b1fc8cb69bb5b0d142f5f2359b96f13646a4ded/src/setup-ocaml/installer.ts#L40

**Comment by smorimoto** [comment]
The pre-release opam has native depext support and is available with the following input: `allow-prerelease-opam`
