### ISSUE TITLE
Can't use Cygwin, bad URL?

### ISSUE THREAD

**Issue by johnridesabike** [ocaml/setup-ocaml#642]
I recently ran this action on Windows and it's failing because it can't download Cygwin:
```
  site: https://cygwin.mirror.constant.com/
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.zst.sig
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.zst
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.xz.sig
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.xz
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.bz2.sig
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.bz2
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.ini.sig
  connection error: 12037 fetching https://cygwin.mirror.constant.com/x86_64/setup.ini
  mbox note: Unable to get setup from <https://cygwin.mirror.constant.com/>
  unattended_mode is set at mbox: returning default value
  download/verify error in unattended_mode: out of retries
  note: Installation incomplete.  Check D:\cygwin\var\log\setup.log.full for details
  Ending cygwin install
  Error: The process 'C:\hostedtoolcache\windows\cygwin\3.4.3\x86_64\setup-x86_64.exe' failed with exit code 1
```

It looks like cygwin.mirror.constant.com does not support HTTPS, only HTTP. At first I wondered if this was just an error with the mirror (and would hopefully resolve itself later), but I see that the Cygwin website lists this particular mirror as only supporting HTTP as well: https://www.cygwin.com/mirrors.html

> New Jersey: [cygwin.mirror.constant.com](http://cygwin.mirror.constant.com/) (http)

Relevant line from `setup-ocaml`:
https://github.com/ocaml/setup-ocaml/blob/1c10d36d08dc61f2398233c37e815e075e2a4a0e/src/setup-ocaml/cache.ts#L122

**Comment by smorimoto** [comment]
Oops. That's bad. Let me release a fix soon.

**Comment by smorimoto** [comment]
Fixed in https://github.com/ocaml/setup-ocaml/releases/tag/v2.0.9...
