### ISSUE TITLE
Add support for ocaml-system

### ISSUE THREAD

**Issue by Kakadu** [ocaml/setup-ocaml#65]
I want to compile and install a C++ application using opam so I need opam but can skip installing OCaml. 
It looks like that OCaml versions specified in yml file are passed in `opam switch` command directly and I can't say `system` instead of compiler version. Can you clarify this part of README?

**Comment by Kakadu** [comment]
Well, I thought a little bit more and maybe I do not need this action in my case..

**Comment by smorimoto** [comment]
There is currently a project called actions-ml to reduce compilation time. The interface is exact same and the setup time is less than one minute. It will be released as an official action soon.
https://github.com/actions-ml/setup-ocaml

**Comment by Kakadu** [comment]
Thanks, I will wait your announce on https://discuss.ocaml.org/

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by smorimoto** [comment]
You will be able to use the system compiler from v2. But I don't recommend that because it's fast enough with the caching feature.
