### ISSUE TITLE
Bring back Cygwin git (optionally?)

### ISSUE THREAD

**Issue by cknitt** [ocaml/setup-ocaml#650]
In 2.0.11 / https://github.com/ocaml/setup-ocaml/pull/648, Cygwin's git was removed.

This broke our CI because of some weird behavior regarding newlines with the default git binary, see https://github.com/rescript-lang/rescript-compiler/pull/6034.

Would it be possible to bring back Cygwin's git (maybe only if some option is specified)?

**Comment by dra27** [comment]
Thanks for reporting this! I've had a poke, and it turns out it's not #648 which is to blame, but unfortunately my shim fix for opam-repository in #647! 😱

**Comment by cknitt** [comment]
Hi @dra27, thanks a lot for the quick fix! 👍 Glad to hear that the issue was not the Git binary, sorry for the incorrect bug report!

**Comment by dra27** [comment]
No problem at all, @cknitt - thanks for reporting the issue, rather than only pinning to the old version!
