### ISSUE TITLE
Missing patches/failed builds

### ISSUE THREAD

**Issue by mgree** [ocaml/setup-ocaml#665]
Several 4.x builds of OCaml are failing:

 - https://github.com/mgree/smoosh/actions/runs/5131589007/jobs/9240361537#step:3:101
 - https://github.com/mgree/smoosh/actions/runs/5131589007/jobs/9240361095#step:3:822

It's not clear to me whether or not this is an upstream issue or something that can be resolved in the action.

**Comment by smorimoto** [comment]
It's probably not an issue of this action, it's related to https://github.com/ocaml/opam-repository/issues/23837, which has already been fixed upstream.
