### ISSUE TITLE
Error on apt-get fetch

### ISSUE THREAD

**Issue by 3Rafal** [ocaml/setup-ocaml#667]
When running setup-ocaml, I consistently get an error:
```
  E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/g%2b%2b-11-multilib_11.3.0-1ubuntu1%7e22.04_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
  Error: The process '/usr/bin/sudo' failed with exit code 100
```
You can see the failed build here:
https://github.com/3Rafal/merl-an/actions/runs/5188437327/jobs/9352080331#step:3:112

This doesn't fail the whole job, but is shown in annotations:
<img width="694" alt="image" src="https://github.com/ocaml/setup-ocaml/assets/22241847/1f3e415c-8406-4c33-83f0-e0176b04cf37">

The logic that is responsible for this behavior is in function `initializeOpamUnix`:
```ts
async function initializeOpamUnix() {
  try {
    await installUnixSystemPackages();
  } catch (error) {
    if (error instanceof Error) {
      core.error(error.message);
    }
    await updateUnixPackageIndexFiles();
    await installUnixSystemPackages();
```

The idea is that we:
1. Run `apt-get install` via `installUnixSystemPackages`
2. We get an error wich is caught
3. We run `apt-get update` via `updateUnixPackagesIndexFiles`
4. We run `apt-get install` once again and now it works fine.

I wonder if we can omit the step 1 and 2?
Then we will just do `apt-get update` and `apt-get install` once in a correct order.

**Comment by 3Rafal** [comment]
It seems to be fixed, nvm

**Comment by smorimoto** [comment]
In general, index files are rarely corrupted, and inserting an update step for them means extra setup time. I introduced an improvement for it in the latest release. You should be able to check the results here: https://github.com/ocaml/setup-ocaml/actions/runs/5164993889
