### ISSUE TITLE
Custom compiler options for ocaml >= 4.12

### ISSUE THREAD

**Issue by Gbury** [ocaml/setup-ocaml#67]
Trying to specify an `ocaml-version` of `4.12.0+flambda` in the action does not work (whereas `4.11.2+flambda` works).

As far as I know, it's because opam has changed a bit how compiler options are handled since ocaml 4.12, more specifically, whereas before there was packages for the ocaml compiler such as `4.11.2+flambda` or `4.11.2+32bit`, they are no longer present for `4.12.0`, instead being replace by a package `4.12.0+options` as well as individual packages for each configuration option. The recommended (or at least one) way to create such switches is now:
```
opam switch create test ocaml-variants.4.12.0+options ocaml-option-32bit
```

However, since when one uses the `setup-ocaml` action, one does not create the switch manually, what should one specify in `ocaml-version` to get say, a 4.12.0 compiler with flambda enabled ? (or with the 32-bit option, which although still targeting 64-bit architectures, seems the easiest way to check that sources will compile on 32-bit distributions)

**Comment by smorimoto** [comment]
That's exactly what I plan to support in v2. You can use `@v2` instead to enable it because we are already working with the branch name that is compatible with future v2 release: #66

**Comment by Gbury** [comment]
Thanks, did that and it almost works (cf #68 ) !
