### ISSUE TITLE
Allow to use prereleases from opam

### ISSUE THREAD

**Issue by jchavarri** [ocaml/setup-ocaml#698]
opam 2.2 has been in alpha for [a few months](https://opam.ocaml.org/blog/opam-2-2-0-alpha/). It would be nice to allow users of setup-ocaml to test new versions of opam before they have been released officially, in order to test their packages for new versions of opam in ci.

I was able to work around by forking this action and [tweaking its code](https://github.com/ocaml/setup-ocaml/compare/master...jchavarri:setup-ocaml:opam-v2), but things would be more convenient if there was a flag in the action configuration directly.

**Comment by smorimoto** [comment]
Sounds good.

**Comment by smorimoto** [comment]
@jchavarri See https://github.com/ocaml/setup-ocaml/issues/698.
