### ISSUE TITLE
Is setting OPAM_CLI from the action necessary?

### ISSUE THREAD

**Issue by jchavarri** [ocaml/setup-ocaml#709]
Currently, it is possible to use opam 2.2 through the [recently added](https://github.com/ocaml/setup-ocaml/pull/704) `allow-prelease-opam` config (thanks!).

However, when one tries to use features from this version, like the `--with-dev-setup` flag, opam will error with:

```
opam: --with-dev-setup was added in version 2.2 of the opam CLI, but version 2.0 has been requested, which is older.
```

The reason for this is that `setup-ocaml` will set `OPAMCLI` to 2.0 here:

https://github.com/ocaml/setup-ocaml/blob/06476c10907d79756d879c7e1afaf711a94f2a2f/packages/setup-ocaml/src/installer.ts#L38

I wonder if setting this config in the action is strictly necessary? Wouldn't it be easier to just leave this version "float" and have opam used the latest version available?

**Comment by smorimoto** [comment]
See #711 🙂

**Comment by jchavarri** [comment]
Nice! For the record, I managed to work around the original issue by passing `--cli` flag to the `opam` command. Just mentioning in case the changes in #711 were somehow controversial, for some reason (maybe it's better to stick with a default version in all cases, idk).

**Comment by smorimoto** [comment]
It's true that you can use `--cli` to avoid the issue, but in cases where you want to allow pre-release, the environment variable is just noisy, so it seems sensible to leave it unset.

**Comment by smorimoto** [comment]
Shipped: https://github.com/ocaml/setup-ocaml/releases/tag/v2.1.1
