### ISSUE TITLE
OPAMCONFIRMLEVEL=unsafe-yes causes many warnings

### ISSUE THREAD

**Issue by emillon** [ocaml/setup-ocaml#728]
Hi,
Since setup-ocaml v2.1.5, we're seeing many warnings like:

```
Warning:  OPAMCONFIRMLEVEL was ignored because CLI 2.0 was requested and it was introduced in 2.1.
```

Because opam is used in our test suite, this is causing some cram test failures.
This is difficult to work around because there is no easy way to unset environment variables in github actions.

**Comment by smorimoto** [comment]
OK - I will create a PR to fix this.

**Comment by smorimoto** [comment]
Fixed in https://github.com/ocaml/setup-ocaml/releases/tag/v2.1.7.
