### ISSUE TITLE
[Windows] opam refers to paths that are not valid from any default shell

### ISSUE THREAD

**Issue by JasonGross** [ocaml/setup-ocaml#73]
I am trying to debug a failure at https://github.com/mit-plv/fiat-crypto/pull/966/checks?check_run_id=2530006424
`opam` claims
```
#=== ERROR while compiling coq-fiat-crypto.dev ================================#
# context              2.0.8 | win32/x86_64 | ocaml-variants.4.11.1+mingw64c | https://coq.inria.fr/opam/extra-dev#2021-05-07 10:10
# path                 ~/.opam/ocaml-variants.4.11.1+mingw64c/.opam-switch/build/coq-fiat-crypto.dev
# command              D:\cygwin\bin\make.exe -j3 EXTERNAL_DEPENDENCIES=1 SKIP_BEDROCK2=1 coq-without-bedrock2 standalone-ocaml
# exit-code            2
# env-file             ~/.opam/log/coq-fiat-crypto-3352-d6d332.env
# output-file          ~/.opam/log/coq-fiat-crypto-3352-d6d332.out
### output ###
```
but when I `cat ~/.opam/log/*` from powershell, I get
```
Line |
   2 |  cat ~/.opam/log/*
     |  ~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\runneradmin\.opam\log' because it does not exist.
```
Am I supposed to run `opam exec -- cat ~/.opam/log/*` instead?  The documentation here does not seem to say, so I'll try it.  I suspect from the explanation in https://github.com/avsm/setup-ocaml/issues/71#issuecomment-832486222 that it won't work.  I can't set the shell to `bash` and have that work either, though, as discovered in https://github.com/avsm/setup-ocaml/issues/71#issuecomment-832486222.  So I guess I'm stuck explicitly passing the path to cygwin's bash?

**Comment by smorimoto** [comment]
v2 is exporting `OPAMROOT`. The reason we don't use the home directory, which is known as the C drive, is that Azure temporary drive has much higher performance. (See https://github.com/avsm/setup-ocaml/pull/55)

**Comment by dra27** [comment]
opam displays the substitution `~` for a prefix which matches `%HOME%` at the point at which it ran. So I expect it's running from within Cygwin's bash and is therefore referring to `D:\cygwin\home\runneradmin\.opam\log`?
