### ISSUE TITLE
Windows opam version is old

### ISSUE THREAD

**Issue by Alizter** [ocaml/setup-ocaml#731]
The Windows opam version appears to be 2.0.10 according to https://github.com/ocaml/dune/actions/runs/7098545477/job/19320727516?pr=9372 compared to 2.1.5 for Linux.

Why are these different?

**Comment by Leonidas-from-XIV** [comment]
@smorimoto Can we have a newer OPAM on Windows please? The old version doesn't seem to support opam files in a subdirectory and thus CI jobs that work on Unix fail on Windows.

**Comment by smorimoto** [comment]
I would like to work on that, but I could not do it this year because of a lot of other things to do. Also, I put it off because the latest opam is not yet officially supported and is not very straightforward. If someone could sponsor the work, that would be fantastic 🤷‍♂️

**Comment by smorimoto** [comment]
Let's track this in a new issue: #733
