### ISSUE TITLE
Native Windows Support

### ISSUE THREAD

**Issue by smorimoto** [ocaml/setup-ocaml#733]
Fill out later!

**Comment by smorimoto** [comment]
Ref: https://github.com/ocaml/setup-ocaml/issues/664, https://github.com/ocaml/setup-ocaml/issues/720, https://github.com/ocaml/setup-ocaml/issues/731

**Comment by aryx** [comment]
When setup-ocaml will use a more recent opam version in Windows? Right now we can't build semgrep on windows because
we require opam 2.1.0.
