### ISSUE TITLE
Running act without requiring a GitHub token

### ISSUE THREAD

**Issue by dannywillems** [ocaml/setup-ocaml#755]
As mentioned in https://github.com/ocaml/setup-ocaml/issues/211, we need to have a GitHub token to run using act.
Is there a solution we can implement to avoid this?

**Comment by dannywillems** [comment]
FWIW, the permissions required on the token is simply the `user` category.

**Comment by smorimoto** [comment]
It would be hard to avoid, and we don't have a strong enough incentive to do it.
