### ISSUE TITLE
opam update should be retried if connection times out

### ISSUE THREAD

**Issue by JasonGross** [ocaml/setup-ocaml#78]
It'd be nice to retry opam update a couple of times of it times out (perhaps based on a max retries parameter for the action), so I don't have to restart all jobs when one fails on a transient error.  See https://github.com/mit-plv/fiat-crypto/runs/2570073992?check_suite_focus=true#step:2:496

**Comment by dra27** [comment]
Possibly - I used to be a fan of automatically retrying things, however having fixed a few things in the past which were masked by automatic retries, I’ve become a little more reticent (an error in Cygwin where fork systematically worked every _other_ call was one and a very obscure test bug in OCaml which happened to surface more regularly on Windows being the the other!)

For things like opam update, it might be worth replicating something closer to what we do in [ocurrent/docker-base-images](https://github.com/ocurrent/docker-base-images) - having a clone of opam-repository earlier in your workflow and using actions cache to share this. It would have the benefit of ensuring that all the macOS and Linux jobs definitely use the same opam-repository, for example.

(I can’t remember, commenting from my phone, if the required support is in setup-ocaml for doing opam init from a different repository - my point is I think features to support the caching workflow above would be better than automatic retries)

**Comment by smorimoto** [comment]
> For things like opam update, it might be worth replicating something closer to what we do in ocurrent/docker-base-images - having a clone of opam-repository earlier in your workflow and using actions cache to share this. It would have the benefit of ensuring that all the macOS and Linux jobs definitely use the same opam-repository, for example.

At the very least, macOS and Ubuntu runners are now forced to use the latest and exact same repository by #109, and Windows runners are forced to use the latest Windows repository.

**Comment by smorimoto** [comment]
I don't think this should be done on the action side at this point, so I will just close for now. If there are any updates in the comments, I will reopen.
