### ISSUE TITLE
[wish] Control the name of the OPAM switch

### ISSUE THREAD

**Issue by corwin-of-amber** [ocaml/setup-ocaml#79]
Some devs find it useful to build in a dedicated switch, and as such their Dune workspace requires a switch with a particular name (e.g. [wacoq](https://github.com/corwin-of-amber/wacoq-bin)).

v1 creates a switch named after the OCaml version, and v2 creates switch `.` (current directory). Would be nice to have a config option for that.

**Comment by dra27** [comment]
With every config option comes the need to test it! The intention behind `dune-workspace` is not necessarily to commit them to repos (as noted in the [manual for `dune-workspace.dev`](https://dune.readthedocs.io/en/stable/dune-files.html#dune-workspace)), precisely because it hard-codes global switch names.

I think it would be better to be setting up `dune-workspace` as part of the workflow - setup-ocaml may be changing the switch type _between major versions_, but this wouldn't change (either type or name) with a given major version.

**Comment by corwin-of-amber** [comment]
We found that having the project always build in its own switch is abundantly comfortable because we have a non-standard version of Coq, and that prevents any confusion that might cause the build to overwrite the general-public Coq. I cannot really vouch for other situations where that is useful (perhaps @ejgallego can comment).

I understand the need to have a `dune-workspace.dev` for that purpose. We will definitely consider it.

**Comment by dra27** [comment]
Indeed - I can certainly see the benefit of having a switch dedicated to the project (although you could also achieve this by recommending the use of a local switch - i.e. `opam switch create .` as the first stage of using the project?), it's definitely just the mechanism of distributing it via `dune-workspace` which I think isn't quite right.

**Comment by ejgallego** [comment]
I feel that more flexibility is needed here, for example I have projects where the build involves multiple switches (first metaocaml, then flambda) , but indeed I guess for that cases setup-ocaml is maybe not the right tool. Builds such as jscoq may involve some trickery with multiple switches too.

**Comment by dra27** [comment]
setup-ocaml isn’t (I hope!) stopping that flexibility - you can still set-up and cache whatever you want in the workflow! My only suggestion is that it would be better to your tailor the _main_ switch around what setup-ocaml does rather than the other way around

**Comment by smorimoto** [comment]
If you want something that isn't a local switch, it requires quite a bit of code change, which causes quite a few (mostly cache-related) challenges. With that in mind, I would like to agree with @dra27's comment.

**Comment by smorimoto** [comment]
After rethinking this, it shouldn't be that complicated, but again, @dra27's point makes sense, so I will close this for now. But don't hesitate to drop comments if I miss something important! I'm ready to reopen this quickly.
