### ISSUE TITLE
opam 2.2 support on Windows

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/setup-ocaml#793]
The following code https://github.com/ocaml/setup-ocaml/blob/1903ece104ed71374b15d2bc25624ed60721c0ab/packages/setup-ocaml/src/constants.ts#L45-L46 disallows the use of the latest opam beta which is compatible with Windows.

Would it be possible to remove this conditional?

**Comment by hhugo** [comment]
One need to change acquireOpamWindows to take the pre release into account

**Comment by smorimoto** [comment]
This is related to this issue: #733
