### ISSUE TITLE
Support for multiple opam repositories

### ISSUE THREAD

**Issue by na4zagin3** [ocaml/setup-ocaml#80]
Hi!

I'm trying `v2` version https://github.com/ocaml/setup-ocaml/commit/fc46ffdb271cdf64564698186b7d4030b0803acf of this action at https://github.com/na4zagin3/satyrographos-repo/pull/309 but it doesn't work well ([check_run_id=2645592823](https://github.com/na4zagin3/satyrographos-repo/pull/309/checks?check_run_id=2645592823)) because `*.opam` files at the project root depends on packages at multiple custom OPAM repos in addition to the OPAM official repo.

As far as I understand, v2 (https://github.com/ocaml/setup-ocaml/pull/66) doesn't support custom OPAM repos at this moment.  If so, can it have another input parameter, for example, CUSTOM_REPOSITORIES or OVERLAY_REPOSITORIES, that takes a comma-separated list of `<repo-name>=<repo-url>` like [`--repos=` option of `opam switch create` subcommand](https://opam.ocaml.org/doc/Manual.html#Repositories)?

<details>
<summary><a href="https://github.com/na4zagin3/satyrographos-repo/pull/309/checks?check_run_id=2645592823">Output from the action v2</a></summary>

```
Set up OCaml 4.11.1
Warning: Unexpected input(s) 'ocaml-version', valid inputs are ['ocaml-compiler', 'opam-repository', 'opam-pin', 'opam-depext', 'opam-depext-flags', 'opam-local-packages', 'opam-disable-sandboxing', 'dune-cache', 'cache-prefix', 'github-token']
▸ Run avsm/setup-ocaml@v2
▸ Retrieve the opam cache
▸ Install opam
▸ Initialise the opam state
▸ Install OCaml
▸ Save the opam cache
▸ Retrieve the opam download cache
▸ Install depext
▸ Retrieve the dune cache
▸ Install dune
▾ Pin local packages
Install system packages required by opam packages
  /opt/hostedtoolcache/opam/2.0.8/x86_64/opam depext snapshot-develop snapshot-stable-0-0-4 snapshot-stable-0-0-5 snapshot-stable-0-0-6 
  # Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
  [ERROR] No solution for snapshot-develop & snapshot-stable-0-0-4 & snapshot-stable-0-0-5 & snapshot-stable-0-0-6: The following dependencies couldn't be met:
            - snapshot-stable-0-0-5 → satysfi
                unknown package
  
  
  Command failed: opam list --readonly --external  '--resolve=snapshot-develop,snapshot-stable-0-0-4,snapshot-stable-0-0-5,snapshot-stable-0-0-6,' returned 20
  Error: The process '/opt/hostedtoolcache/opam/2.0.8/x86_64/opam' failed with exit code 20
```
</details>

(Transferred from https://github.com/actions-ml/setup-ocaml/issues/7)

**Comment by smorimoto** [comment]
If the custom repository does not work alone, the current workaround is to disable `opam-pin` and `opam-depext`. If it works alone, in other words, if you don't need the default repository, you can just pass it to the `opam-repository` input.

**Comment by smorimoto** [comment]
The functionality to support multiple repositories (e.g. default and multicore repositories) will be implemented soon. After that, no workaround is needed.

**Comment by na4zagin3** [comment]
Thank you for your quick responses!

In this case, to disable `opam-pin` and `opam-depext` should work since the custom OPAM repos I mentioned are “custom repository overlays,” which don't work alone.  Let me try it.

**Comment by na4zagin3** [comment]
Thank you!
