### ISSUE TITLE
3.0.0-alpha: error on Windows

### ISSUE THREAD

**Issue by cknitt** [ocaml/setup-ocaml#812]
I just tried 3.0.0-alpha, see https://github.com/rescript-lang/rescript-compiler/actions/runs/9576805424/job/26403964492?pr=6819.

On Windows, I got the following error:

```
Run opam install . --deps-only
opam: D:\a\_temp\410aa59a-3971-4df1-b31f-4d0c6ee7b04d.ps1:2
Line |
   2 |  opam install . --deps-only
     |  ~~~~
     | The term 'opam' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
Error: Process completed with exit code 1.
```

On the other platforms, I got the following warning:

```
Warning: Unexpected input(s) 'opam-depext', valid inputs are ['allow-prerelease-opam', 'ocaml-compiler', 'opam-repositories', 'opam-pin', 'opam-local-packages', 'opam-disable-sandboxing', 'dune-cache', 'cache-prefix', 'github-token']
```

**Comment by hhugo** [comment]
There is a typo in you file. You're currently not using setup-ocaml on windows.
https://github.com/rescript-lang/rescript-compiler/actions/runs/9576805424/workflow?pr=6819#L218

**Comment by cknitt** [comment]
🤦 Sorry about that!!! Forgot to remove that line and then overlooked that setup-ocaml was not called at all for Windows.

However, it still does not work, I am now getting

```
Warning: Unexpected input(s) 'opam-depext', valid inputs are ['allow-prerelease-opam', 'ocaml-compiler', 'opam-repositories', 'opam-pin', 'opam-local-packages', 'opam-disable-sandboxing', 'dune-cache', 'cache-prefix', 'github-token']
Run ocaml/setup-ocaml@v3.0.0-alpha
Change the file system behaviour parameters
Retrieve the opam cache
Error: Could not find any assets matching the current platform or architecture
```

https://github.com/rescript-lang/rescript-compiler/actions/runs/9591803929/job/26449391197?pr=6819

**Comment by hhugo** [comment]
I think you need allow-prerelease-opam: true 
Also, opam-depext is now useless

**Comment by cknitt** [comment]
Sorry again for bothering you. Works perfectly fine when supplying the correct parameters.

It is great that things are now working on Windows out of the box without any special configuration required anymore (other than the allow-prerelease-opam)! Thanks a lot for your work!

**Comment by smorimoto** [comment]
You have nothing to apologise for!
Yes, the gap between Windows and Unix in OCaml is getting smaller and smaller thanks to David!
