### ISSUE TITLE
3.0.0-alpha: Windows: bash script fails with "syntax error: unexpected end of file"

### ISSUE THREAD

**Issue by cknitt** [ocaml/setup-ocaml#815]
Another 3.0.0-alpha issue, I hope this one makes more sense than my previous one 🙈.

So once correctly configured, setup-ocaml itself works perfectly fine on Windows, and we can use the OCaml 5.2.0 compiler to build our project.

However, after the setup-ocaml step and our successful OCaml build step, we have the following step:

```yml
      - name: "Check if syntax subfolder has changed"
        id: syntax-diff
        shell: bash
        run: |
          if git diff --name-only --exit-code HEAD^ HEAD -- jscomp/syntax; then
            echo "syntax_status=unchanged" >> $GITHUB_ENV
          else
            echo "syntax_status=changed" >> $GITHUB_ENV
          fi
```

This step works fine when using setup-ocaml 2.x.x, but fails with 3.0.0-alpha with the following error message:

```
Run if git diff --name-only --exit-code HEAD^ HEAD -- jscomp/syntax; then
D:\a\_temp\d426cc8d-884f-4bdc-a18e-a[70](https://github.com/rescript-lang/rescript-compiler/actions/runs/9594206863/job/26456471252?pr=6819#step:18:71)af2c1cc23.sh:
line 6: syntax error: unexpected end of file
Error: Process completed with exit code 2.
```

So it seems that the setup-ocaml step changes something in the environment, causing this error.

See https://github.com/rescript-lang/rescript-compiler/actions/runs/9601379213/job/26481410755.

**Comment by smorimoto** [comment]
This issue is probably unrelated to the action.

**Comment by cknitt** [comment]
> Remove this step: https://github.com/rescript-lang/rescript-compiler/actions/runs/9601379213/workflow#L183-L187

I should have mentioned that I have already tried this, but it didn't help. Also, this did work fine with the setup-ocaml 2.x.x.

This is definitely a new issue with 3.0.0-beta.
Here is a standalone repro:

https://github.com/cknitt/setup-ocaml-repro/blob/main/.github/workflows/ci.yml
https://github.com/cknitt/setup-ocaml-repro/actions/runs/9745608001/job/26893980512

So please reopen this issue @smorimoto

**Comment by smorimoto** [comment]
The Actions runner may be using the wrong bash:

<img alt="image" src="https://github.com/ocaml/setup-ocaml/assets/38746192/37d49e84-0dfe-43ad-a123-dd2b3c784925">

**Comment by smorimoto** [comment]
https://github.com/marketplace/actions/install-cygwin-action#line-endings

**Comment by smorimoto** [comment]
You can use `>-` instead:

```yaml
- name: "Check if syntax subfolder has changed"
  id: syntax-diff
  shell: bash
  run: >-
    if git diff --name-only --exit-code HEAD^ HEAD -- jscomp/syntax; then
      echo "syntax_status=unchanged" >>"$GITHUB_ENV"
    else
      echo "syntax_status=changed" >>"$GITHUB_ENV"
    fi
```

**Comment by cknitt** [comment]
@smorimoto Thanks, but the proposed workaround with `>-` does *NOT* solve the problem.

See

https://github.com/cknitt/setup-ocaml-repro/blob/main/.github/workflows/ci.yml
https://github.com/cknitt/setup-ocaml-repro/actions/runs/9761746852/job/26943486150

Why does the 3.0.0 extension need to modify the path in such a way that a different bash binary becomes the default when that obviously wasn't necessary in 2.x.x?

This particular bash issue may not be the only side effect of this new behavior.

**Comment by cknitt** [comment]
Ah, overlooked the `SHELLOPTS: igncr`, sorry, will try that, too.

However, the question remains: Why this change?

**Comment by cknitt** [comment]
Ok, I can confirm that `SHELLOPTS: igncr` is the correct workaround.

**Comment by smorimoto** [comment]
A better way to set it on Windows only is:

```yaml
- name: Set SHELLOPTS=igncr on Windows
  if: runner.os == 'Windows'
  run: echo "SHELLOPTS=igncr" >>"$GITHUB_ENV"
```

**Comment by smorimoto** [comment]
The reason you need to do this from v3 is that, until v2, the opam you call was not the real opam: https://github.com/ocaml/setup-ocaml/blob/970719e1fee4d99a8f464db850f5ef30028f68c8/packages/setup-ocaml/src/opam.ts#L240-L248

**Comment by ygrek** [comment]
does it make sense to have igncr as default on windows runners?
