### ISSUE TITLE
Documentation for compatibility

### ISSUE THREAD

**Issue by liyishuai** [ocaml/setup-ocaml#828]
In ocaml-community/cppo#88 I had a hard time figuring out which version of setup-ocaml I should use for different (Operating System, OCaml version) pairs. Maybe worth documenting a compatibility mapping (OS * OCamlVersion -> SetupVersion) so that users needn't try it by ourselves?

**Comment by smorimoto** [comment]
Good idea! But I want to just add the latest support table. The latest action obviously uses the latest language platform, and if the necessary support is lacking there, I think it should be addressed across the language platform rather than using older actions. CC: @avsm @dra27
