### ISSUE TITLE
v3 is no longer capable of installing zarith on Windows

### ISSUE THREAD

**Issue by JasonGross** [ocaml/setup-ocaml#833]
```
# binary ocamlfind: found in /cygdrive/d/a/fiat-crypto/fiat-crypto/_opam/bin
# OCaml's word size is 64
# include gmp.h: not found
# include mpir.h: not found
# cannot find GMP nor MPIR
```
https://github.com/mit-plv/fiat-crypto/actions/runs/9921830869/job/27410226547?pr=1925

**Comment by hhugo** [comment]
zarith installs fine (https://github.com/ocsigen/js_of_ocaml/actions/runs/10113804774/job/27970974184)
I think you need to drop the sunset repo `opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset`
