### ISSUE TITLE
dune fails on macOS when dune-cache is enabled

### ISSUE THREAD

**Issue by ivg** [ocaml/setup-ocaml#88]
I am aware that dune-cache is not yet supported on macOS, but would be at least possible to prevent the builds from [failing][1] if it is set, e.g., by not setting the option on macOS, or setting it to `disabled`?

Maybe there is an obvious workaround that I am missing?

[1]: https://github.com/BinaryAnalysisPlatform/bap/pull/1313/checks?check_run_id=2667855657#step:8:586

**Comment by smorimoto** [comment]
For example, this expr allows us to do that!

```
dune-cache: ${{ matrix.os != 'macos-latest' }}
```

**Comment by smorimoto** [comment]
And it's what I'm doing here: https://github.com/BinaryAnalysisPlatform/bap/pull/1312

**Comment by ivg** [comment]
thank you so much! I wish I noticed your PR earlier))

**Comment by smorimoto** [comment]
No worries at all!

**Comment by smorimoto** [comment]
Resolved with https://github.com/ocaml/opam-repository/pull/20758.
