### ISSUE TITLE
`opam pin` fails with "No switch is currently set` with v2

### ISSUE THREAD

**Issue by ivg** [ocaml/setup-ocaml#90]
After the switch to v2 we have a strange [failure][1] when we try to `opam pin` a package. I am not sure if this is a bug (probably something with caching) or a difference in the semantics of setup-ocaml@v2 action. 

[1]: https://github.com/BinaryAnalysisPlatform/bap/runs/2672235378?check_suite_focus=true#step:10:1

**Comment by smorimoto** [comment]
It looks more like an opam and local switch problem than a cache problem, but this is rather weird.

**Comment by smorimoto** [comment]
Do you have any idea about this? @dra27

**Comment by ivg** [comment]
Yep, and it only fails on pin,  `opam install` worked perfectly fine.

**Comment by dra27** [comment]
What happens if you change the `cache-prefix` parameter (in order to ensure that the caches are all invalid) - does it work the first time and then not on re-runs?

**Comment by ivg** [comment]
Another interesting observation is that nearly all our workflows use exactly the same trick [[1],[2]] `opam pin add bap . -n` with only the nightly-build failing on it. Maybe it's sporadic? I restarted the build just to get sure that it is reproducible. Then I will try to restart it with a different cache-prefix and restart it a couple of times. 

[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/.github/workflows/build-and-test.yml#L32
[2]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/.github/workflows/build-dev-repo.yml#L40

**Comment by ivg** [comment]
It's reproducible, i.e., rerunning without changing the cache-prefix ended up with the same failure.

**Comment by ivg** [comment]
and, finally, tried with a different [cache-prefix][1] and failed with the same error. 


[1]: https://github.com/BinaryAnalysisPlatform/bap/runs/2687999059?check_suite_focus=true#step:2:15

**Comment by ivg** [comment]
Any updates, ideas?

**Comment by smorimoto** [comment]
I think #109 should solve the problem. This error is caused by the absence of a global switch, but this PR also handles it well.
