### ISSUE TITLE
Error: utimes: C:\Users\runneradmin\Local Settings\Cache\dune\db\beacon: on windows-latest, 4.04.2 with dune cache enabled

### ISSUE THREAD

**Issue by shonfeder** [ocaml/setup-ocaml#94]
We are hitting a failure when `dune-cache = true` on `windows-latest` and compiler version `4.04.2`.

You can see the run here: https://github.com/ocaml/omd/pull/241/checks?check_run_id=2701390163

Disabling `dune-cache` resolves the problem: https://github.com/ocaml/omd/pull/241/checks?check_run_id=2701410082

Perhaps this is just a limitation to document? (I didn't see mention of it in the readme).

Thanks for the excellent work!

**Comment by smorimoto** [comment]
To use the dune cache on Windows, you need dune 2.8.5 or later. I think it should be documented so I will add it later.
https://github.com/ocaml/omd/runs/2701390163?check_suite_focus=true#step:3:169

**Comment by shonfeder** [comment]
Makes sense. Thanks!

**Comment by smorimoto** [comment]
Resolved with https://github.com/ocaml/opam-repository/pull/20758.
